[build-system]
requires = ["setuptools", "wheel", "numpy==1.24.0"]
build-backend = "setuptools.build_meta"
# The numpy requirement is due to f2py
# see more here: https://github.com/numpy/numpy/issues/24008
# The requirement ought to be removed after f2py is fixed